gamerstore/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_api.viewsLogin import login

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('store.urls')),
    path('api/', include('rest_api.urls')),
    path('login/', login, name='login'),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from .views import home, login ,index, registro, eliminar_usuario, editar_datos, principal, listado_usuarios, terror, accion, aventura, carreras, supervivencia, ver_carrito, pago, eliminar_del_carrito, agregar_al_carrito, listado_juegos, crear_juego, juegos_show, eliminar_juego, juegos_editar, logout_view, recuperar_contrasenna
urlpatterns = [
    # link Juegos
    path('princjuegos/principal', principal, name='principal'),
    path('princjuegos/juegosterror', terror, name="terror"),
    path('princjuegos/juegosaventura', aventura, name="aventura"),
    path('princjuegos/juegosaccion', accion, name="accion"),
    path('princjuegos/juegoscarreras', carreras, name="carreras"),
    path('princjuegos/juegossupervivencia', supervivencia, name="supervivencia"),
    path('princjuegos/ver_carrito', ver_carrito, name="ver_carrito"),
    path('princjuegos/pago', pago, name="pago"),
    path('princjuegos/agregar_al_carrito/<int:juego_id>/', agregar_al_carrito, name="agregar_al_carrito"),
    path('princjuegos/listado_juegos', listado_juegos, name="listado_juegos"),
    path('princjuegos/crearjuego', crear_juego, name="crear_juego"),
    path('princjuegos/<int:id>/editarjuego', juegos_editar, name="juegos_editar"),
    path('princjuegos/<int:id>/juego_show', juegos_show, name="juegos_show"),
    path('princjuegos/<int:id>/eliminar_juego', eliminar_juego, name="eliminar_juego"),
    path('eliminar_del_carrito/<int:juego_id>/', eliminar_del_carrito, name="eliminar_del_carrito"),
    

    # link enlace formularios usuario
    path('inicio_sesion/', login, name="inicio_sesion"),
    path('home/', home, name="home"),
    path('registro/', registro, name="registro"),
    path('eliminar_usuario/<int:id>/', eliminar_usuario, name="eliminar_usuario"),
    path('editar_datos/<int:id>/', editar_datos, name="editar_datos"),
    path('', index, name="index"),
    path('recuperar_contrasenna/', recuperar_contrasenna, name="recuperar_contrasenna"),
    path('princjuegos/listado_usuarios/', listado_usuarios, name="listado_usuarios"),
    path('logout/', logout_view, name="logout")

]

store/models.py
from django.db import models
from django.contrib.auth import get_user_model 
from django.conf import settings


# Create your models here.
class Categoria(models.Model):
    nombre = models.CharField(max_length=200)

    def __str__(self):
        return self.nombre

class Juego(models.Model):
    codigo_invent= models.CharField(max_length=200, unique=True)
    nombre = models.CharField(max_length=200)
    descripcion = models.TextField(null=True, blank=True)
    imagen = models.ImageField(upload_to='juegos/' , null=True , blank=True)
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE, related_name='juegos')
    precio = models.DecimalField(max_digits=10, decimal_places=0)

    def __str__(self):
        return self.get_code_name()

    def get_code_name(self):
        return f" INF: {self.codigo_invent} - {self.nombre}"

class UserProfile(models.Model):
    user = models.OneToOneField(get_user_model(), on_delete=models.CASCADE)
    role = models.CharField(max_length=20, choices=settings.ROLES)

    def __str__(self):
        return self.user.username + ' - ' + self.role
    
class Carrito(models.Model):
    usuario = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    juego = models.ForeignKey(Juego, on_delete=models.CASCADE)
    cantidad = models.PositiveIntegerField(default=1)

store/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Juego, Categoria , UserProfile , Carrito 
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from .decorators import role_requiered
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect
from django.urls import reverse

# definicion sesion de usuarios y perfil
def index(request):
    return render(request, 'auth/index.html')

def login(request):
    if request.method == 'POST':
        usuario = request.POST.get('usuario')
        clave = request.POST.get('pass')

        user = authenticate(request, username = usuario, password = clave)
        if user is not None:
            # Autenticación exitosa
            login(request, user)
            try:
                profile = user.userprofile  # Obtén el perfil de usuario
                request.session['perfil'] = profile.role
            except UserProfile.DoesNotExist:
                # Si el perfil de usuario no existe, puedes manejarlo aquí
                messages.error(request, 'El perfil de usuario no está configurado correctamente.')
                return redirect('index')
            
            return redirect('home')
        else:
            context = {
                'error': 'Error, inténtelo nuevamente'
            }
            return render(request, 'auth/inicio_sesion.html', context)
    return render(request, 'auth/inicio_sesion.html')

@login_required 
def home(request):
    return render(request, 'auth/home.html')
    
@login_required
def listado_usuarios(request):

    users = User.objects.all()
    perfil = request.session.get('perfil') # perfil es el rol, "cliente" o "admin"
    context = {
        'user': users,
        'perfil': perfil,
    }

    return render(request, 'auth/listado_usuarios.html', context)
    
def registro(request):

    if request.method == 'POST':
        first_name = request.POST['first_name']
        username = request.POST['username']
        password = request.POST['password']
        password2 = request.POST['password2']
        email = request.POST['email']
        # Validar los datos ingresados 
        if not username:
            messages.error(request, 'Nombre de usuario es obligatorio')
            return redirect('registro')
        
        if len(password) < 6 or len(password) > 16:
            messages.error(request, 'La contraseña debe tener entre 6 y 16 caracteres')
            return redirect('registro')
        
        if not any(char.isupper() for char in password):
            messages.error(request, 'La contraseña debe contener al menos una letra mayúscula')
            return redirect('registro')

        # Verificar si el nombre de usuario ya existe
        if User.objects.filter(username=username).exists():
            messages.error(request, 'El nombre de usuario ya está en uso')
            return redirect('registro')
        
        if password != password2:
            messages.error(request, 'La contraseña debe ser iguales')
            return redirect('registro')
        
        user = User.objects.create_user(
            first_name=first_name,
            username=username,
            password=password,
            email=email
        )
        # Se asigna rol cliente siempre al registrarse
        role = 'cliente'
        UserProfile.objects.create(user=user, role=role)

        authenticated_user = authenticate(request, username=username, password=password)
        if authenticated_user:
            login(request, authenticated_user)

        messages.success(request, 'Se ha creado la cuenta correctamente como cliente')

        return redirect('listado_usuarios')
        
    else:
        return render(request, 'auth/registro.html')  
    
@role_requiered('admin')
def editar_datos(request,id):
    
        usuario = get_object_or_404(User, id=id)
        
        if request.method == 'POST':
            first_name = request.POST['first_name']
            username = request.POST['username']
            password = request.POST['password']
            email = request.POST['email']
            role = request.POST['role'] 

            usuario.first_name = first_name
            usuario.username = username
            usuario.set_password(password)
            usuario.email = email
            usuario.userprofile.role = role
            usuario.userprofile.save()  
            usuario.save()

            messages.success(request, 'Usuario editado exitosamente.')
            return redirect('listado_usuarios')
        return render(request, 'auth/editar_datos.html', {'usuario': usuario})


def recuperar_contrasenna(request):
    if request.method == 'POST':
        correo = request.POST.get('correo')
        new_pass= "123123"

        try:
            usuario = User.objects.get(email=correo)
            usuario.set_password(new_pass)
            usuario.save()
            messages.success(request, 'La contraseña se actualizo con exito')
            return redirect('index')
        except User.DoesNotExist:
            messages.error(request,'No se encontro ningun usuario con ese correo Electronico')

    return render(request, 'auth/recuperar_contrasenna.html')

@role_requiered('admin')
def eliminar_usuario(request, id):
    usuario = get_object_or_404(User, id=id)
    usuario.delete()
    messages.success(request, 'Se ha Eliminado Correctamente')
    return redirect('listado_usuarios')
    
# Vista para cerrar sesión a un Usuario
def logout_view(request):
    print("Cierre de sesión solicitado")
    logout(request)
    request.session.flush() 
    return redirect('index')

# definiciones para juegos 
@login_required
def principal(request):
    return render(request, 'juegos/principal.html')

@login_required
def accion(request):
        
    juegos_accion = Juego.objects.filter(categoria__nombre='ACCION')
    perfil = request.session.get('perfil')
    context = {
        'juegos_accion': juegos_accion,
        'perfil': perfil,
    }
    return render(request, 'juegos/accion.html',context)
@login_required
def supervivencia(request):

    juegos_supervivencia = Juego.objects.filter(categoria__nombre='SUPERVIVENCIA')
    perfil = request.session.get('perfil')
    context = {
        'juegos_supervivencia': juegos_supervivencia,
        'perfil': perfil,
    }
    return render(request, 'juegos/supervivencia.html', context)
@login_required
def terror(request):

    juegos_terror = Juego.objects.filter(categoria__nombre='TERROR')
    perfil = request.session.get('perfil')
    context = {
        'juegos_terror': juegos_terror,
        'perfil': perfil,
    }
    return render(request, 'juegos/terror.html',context)
@login_required
def aventura(request):

    juegos_aventura = Juego.objects.filter(categoria__nombre='AVENTURA')
    perfil = request.session.get('perfil')
    context = {
        'juegos_aventura': juegos_aventura,
        'perfil': perfil,
    }
    return render(request, 'juegos/aventura.html',context)
@login_required
def carreras(request):

    juegos_carreras = Juego.objects.filter(categoria__nombre='CARRERAS')
    perfil = request.session.get('perfil')
    context = {
        'juegos_carreras': juegos_carreras,
        'perfil': perfil,
    }
    return render(request, 'juegos/carreras.html',context)

@login_required
def agregar_al_carrito(request, juego_id):
    juego = get_object_or_404(Juego, id=juego_id)
    user_profile = UserProfile.objects.get(user=request.user)

    if Carrito.objects.filter(usuario=user_profile, juego=juego).exists():
        carrito_item = Carrito.objects.get(usuario=user_profile, juego=juego)
        carrito_item.cantidad += 1
        carrito_item.save()
    else:
        Carrito.objects.create(usuario=user_profile, juego=juego)
    
    return HttpResponseRedirect(reverse('listado_juegos'))

@login_required
def ver_carrito(request):
    user_profile = None
    carrito = []

    if request.user.is_authenticated:
        try:
            user_profile = request.user.userprofile
            carrito = Carrito.objects.filter(usuario=user_profile)
        except UserProfile.DoesNotExist:
            pass

    if carrito is not None:
        total = sum(item.juego.precio * item.cantidad for item in carrito)
    else:
        total = 0
    context = {
            'carrito': carrito,
            'perfil': user_profile,
            'total': total
        }
    
    return render(request, 'juegos/ver_carrito.html', context)

@login_required
def eliminar_del_carrito(request, juego_id):
    juego = get_object_or_404(Juego, id=juego_id)
    
    Carrito.objects.filter(usuario=request.user.userprofile, juego=juego).delete()
    

   
    return redirect('ver_carrito')

@login_required
def pago(request):
    return render(request, 'juegos/pago.html')

@login_required
def juegos_show(request, id):
    juego = get_object_or_404(Juego, id=id)
    context = {
        'juego' : juego
         }

    return render(request, 'juegos/juegos_show.html',context)

@login_required
def listado_juegos (request):
    juegos = Juego.objects.all()

    perfil = request.session.get('perfil')

    context ={
        'juegos' : juegos,
        'perfil' : perfil
    }
    return render (request, 'juegos/listado_juegos.html',context)

@role_requiered('admin')
def juegos_editar(request,id):
    juego = get_object_or_404(Juego, id=id)
    
    if request.method =='POST':
        categoria_id = request.POST.get ('categoria')
        categoria = get_object_or_404(Categoria, id=categoria_id)    

        juego.nombre = request.POST['nombre']

store/templates/juegos/accion.html
{% extends 'base.html' %}




{% block contenido %}
<h1>Juegos ACCIÓN</h1>
<div class="container">
  <div class="row">
    
      {% for juego in juegos_accion %}
 
    
      <div class="col-12 col-sm-6 col-md-4 mb-4">
        <div class="card">
          <a href= "{% url 'juegos_show' id=juego.id %}">
          <img src="{{ juego.imagen.url }}" class="card-img-top" alt="...">
          <div class="card-body">
            <h2 class="card-title"> {{juego.nombre}} </h2>
            </a>
            <p class="card-text">{{ juego.descripcion }}</p>
            <a href="{% url 'agregar_al_carrito' juego.id %}" class="btn btn-primary">Añadir al carrito</a>
          </div>
        </div>
      </div>
    
  
      {% endfor %}
    
  </div>
</div>
<footer>

  <h5> @Copyright Lhia Cadiz /Juan Miranda </h5>

</footer>
{% endblock %}

store/templates/juegos/aventura.html
{% extends 'base.html' %}



{% block contenido %}
<h1>Juegos AVENTURA</h1>
<div class="container">
  <div class="row">
    
      {% for juego in juegos_aventura %}
 
    
      <div class="col-12 col-sm-6 col-md-4 mb-4">
        <div class="card">
          <a href= "{% url 'juegos_show' id=juego.id %}">
          <img src="{{ juego.imagen.url }}" class="card-img-top" alt="...">
          <div class="card-body">
            <h2 class="card-title"> {{juego.nombre}} </h2>
            </a>
            <p class="card-text">{{ juego.descripcion }}</p>
            <a href="{% url 'agregar_al_carrito' juego.id %}" class="btn btn-primary">Añadir al carrito</a>
          </div>
        </div>
      </div>
    
  
      {% endfor %}
    
  </div>
</div>
<footer>

  <h5> @Copyright Lhia Cadiz /Juan Miranda </h5>

</footer>
{% endblock %}


store/templates/juegos/carreras.html
{% extends 'base.html' %}



{% block contenido %}
<h1>Juegos CARRERAS</h1>
<div class="container">
  <div class="row">
    
      {% for juego in juegos_carreras %}
 
    
      <div class="col-12 col-sm-6 col-md-4 mb-4">
        <div class="card">
          <a href= "{% url 'juegos_show' id=juego.id %}">
          <img src="{{ juego.imagen.url }}" class="card-img-top" alt="...">
          <div class="card-body">
            <h2 class="card-title"> {{juego.nombre}} </h2>
            </a>
            <p class="card-text">{{ juego.descripcion }}</p>
            <a href="{% url 'agregar_al_carrito' juego.id %}" class="btn btn-primary">Añadir al carrito</a>
          </div>
        </div>
      </div>
    
  
      {% endfor %}
    
  </div>
</div>
<footer>

  <h5> @Copyright Lhia Cadiz /Juan Miranda </h5>

</footer>
{% endblock %}

store/templates/juegos/crearjuego.html
{% extends 'base.html' %}



{% block css %}
{% endblock %}


{% block contenido %}
<div class = "container">
            <div class="row justify-content-center">
                <div class="col-md-6">
                    
                    <h1 class="text-center">Nuevo Juego</h1>
                    <a href="{% url 'listado_juegos' %}" class="btn btn-dark">Volver</a>
    
                    {% if messages %}
                    {% for message in messages %}
                      <div class="alert alert-{{message.tags}} alert-dismissible fade show" role='alert'>
                        {{ message }}
                        <button type= "button" class="btn-close" data-bs-dissmiss="alert" aria-label="close"></button>
                      </div>
                    {% endfor %}
                    {% endif %}
    
                    <div class="card">
                        <div class="card-body">
                            <form action="" id="formulario" method="POST" enctype="multipart/form-data">
                              {% csrf_token %}
    
                              
                              <div class="mb-3" id="div-cargo">
                                <label for="" class="form-label">Codigo</label>
                                <input type="text" class="form-control" id="codigo_invent"  name="codigo_invent" placeholder="">
                              </div>
    
                              <div class="mb-3">
                                <label for="" class="form-label">NOMBRE</label>
                                <input type="text" class="form-control" id="nombre" name="nombre" placeholder="" required>
                                
                              </div>
    
                              <div class="mb-3" id="div-cargo">
                                <label for="Descripcion" class="form-label">Descripcion</label>
                                <textarea name="descripcion" class="form-control" id="Descripcion"  cols="10" row="5" placeholder=""></textarea>
                              </div>
    
                              <div class="mb-3">
                                <label for="" class="form-label">Categoria</label>
                                <select class="form-select" aria-label="Default select example" name="categoria">
                                {% for categoria in categorias %}
                                    <option value="{{ categoria.id }}">{{ categoria.nombre }}</option>
                                {% endfor %}
                                </select>
                              </div>
                              <div class="mb-3">
                                <label for="" class="form-label">Imagen</label>
                                <input type="file" class="form-control" id="imagen"  name="imagen" >
                              </div>
                              <div class="mb-3">
                              <label for="id_precio"class="form-label">Precio : </label>
                              <input type="number" id="id_precio" name="precio" min="0">
                              </div>
                              <div class="d-grid">
                                  <button type="submit" class="btn btn-outline-primary">GUARDAR</button>
                              </div>
                            </form>
                        </div>
                      </div>
                </div>
               
            </div>
        </div>
{% endblock %}


store/templates/juegos/detalle_juego.html
{% extends 'base.html' %}

{% block css %}
    
{% endblock %}


{% block contenido %}

<h1>Juegos SAGA</h1>


  <div class="container">
      <div class='row' id="personajes">
        
      </div>
  </div>
  <footer>

    <h5> @Copyright Lhia Cadiz /Juan Miranda </h5>
  
  </footer>
{% endblock %}

{% block js %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js" integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script>
  $(document).ready(function(){
    const URL = "https://rickandmortyapi.com/api/character";
    var id_personajes = $("#personajes");

    function addPersonajes(personaje){
      id_personajes.append(`

            <div class="col-12 col-sm-6 col-md-4 mb-4">
              <div class='card'>
                <div class="card-header">
                  <img src="${personaje.image}" class="card-img-top" alt="" class="...">
                  <div class="card-body">
                  <br>
                  <h2 class="card-title">${personaje.name}</h2>
                  <br>
                  <p class="card-text">${ personaje.species }</p>
                  <br>
                </div>
              </div>
            </div>
          `)

    }
    function obtenerPersonajes(){
        $.ajax({
            url : URL,
            method : "GET",
            success : function(data){
              console.log(data.results);
              var personajes= data.results;
              personajes.forEach(addPersonajes);
        }
      })
    }
    obtenerPersonajes();
  });
</script>
{% endblock %}

store/templates/juegos/index.html
{% extends 'base.html' %}
{% load static %}


{% block css %}
{% endblock %}


{% block contenido %}

  <br>
  <br>
  <h2>Los más Vendidos</h2>
  <br>
  <br>

  <div class="container">
    <div class="row">
      <div class="col-12 col-sm-6 col-md-6">
        <a href="{% url 'terror' %}" class="text-no-decoracion">
          <div class="card bg-transparent text-white">
            <img src="{% static '/imagenes/terror1.png '%}" class="card-img-top" alt="Resident Evil"
              class="card-img.top shadow">
            <div class="card-body">
              <h5 class="card-title text-center ">Resident Evil</h5>
            </div>
          </div>
        </a>
      </div>

      <div class="col-12 col-sm-6 col-md-6">
        <a href="{% url 'terror' %}" class="text-no-decoracion">
          <div class="card bg-transparent text-white">
            <img src="{% static '/imagenes/terror2.png' %}" class="card-img-top" alt="Dead by Daylight"
              class="card-img.top shadow">
            <div class="card-body">
              <h5 class="card-title text-center ">Dead by Daylight</h5>
            </div>
          </div>
        </a>

      </div>
      <div class="col-12 col-sm-6 col-md-6">
        <a href="{% url 'carreras' %}" class="text-no-decoracion">
          <div class="card bg-transparent text-white">
            <img src="{% static '/imagenes/carreras1.png' %}" class="card-img-top" alt="Gran Turismo 7"
              class="card-img.top shadow">
            <div class="card-body">
              <h5 class="card-title text-center">Gran Turismo 7</h5>
            </div>
          </div>
        </a>

      </div>

      <div class="col-12 col-sm-6 col-md-6">
        <a href="{% url 'accion' %}" class="text-no-decoracion">
          <div class="card bg-transparent text-white">
            <img src="{% static '/imagenes/accion2.png' %}" class="card-img-top" alt="Crackdown 3"
              class="card-img.top shadow">
            <div class="card-body">
              <h5 class="card-title text-center">Crackdown 3</h5>
            </div>
          </div>
        </a>
      </div>

    </div>
  </div>

  <div class="clearfix"></div>

  <footer>

    <h5>&copy;Copyright Lhia Cadiz /Juan Miranda</h5>

  </footer>

{% endblock %}

store/templates/juegos/juegos_editar.html
{% extends 'base.html' %}


{% block css %}
{% endblock %}


{% block contenido %}
<h1>Editar Juego {{ juego.nombre }}</h1>

<div class = "container">
    

            <div class="row justify-content-center">
                <div class="col-md-6">
                  <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                    <a href="{% url 'listado_juegos' %}" class="btn btn-dark  me-md-2">Volver</a>
                  </div>
                  <center>
                  {% if juego.imagen %}
                  <img src="{{ juego.imagen.url }}" alt="{{ juego.nombre }}" width='200px'>
                  {% else %}
                  <p>-</p>
                  {% endif %}
                  </center>
                    
    
                    {% if messages %}
                    {% for message in messages %}
                      <div class="alert alert-{{message.tags}} alert-dismissible fade show" role='alert'>
                        {{ message }}
                        <button type= "button" class="btn-close" data-bs-dissmiss="alert" aria-label="close"></button>
                      </div>
                    {% endfor %}
                    {% endif %}

                    <div class="card">
                        <div class="card-body">
                            <form action="" id="formulario" method="POST" enctype="multipart/form-data">
                              {% csrf_token %}
    
                              
                              <div class="mb-3" id="div-cargo">
                                <label for="" class="form-label">Codigo</label>
                                <input type="text" class="form-control" id="codigo_invent"  name="codigo_invent" value="{{ juego.codigo_invent}}">
                              </div>
    
                              <div class="mb-3">
                                <label for="" class="form-label">NOMBRE</label>
                                <input type="text" class="form-control" id="nombre" name="nombre" value="{{ juego.nombre }}">

                                
                              </div>
    
                              <div class="mb-3" id="div-cargo">
                                <label for="" class="form-label">Descripcion</label>
                                <textarea name="descripcion" class="form-control" id="Descripcion"  cols"10" row="5" placeholder="">{{ juego.descripcion }}</textarea>
                              </div>
    
                              <div class="mb-3">
                                <label for="" class="form-label">Categoria</label>
                                <select class="form-select" aria-label="Default select example" name="categoria">
                                {% for categoria in categorias %}
                                  {% if categoria.id == juego.categoria.id %}
                                    <option value="{{ categoria.id }}" selected>{{ categoria.nombre }}</option>
                                  {% else %}
                                    <option value="{{ categoria.id }}">{{ categoria.nombre }}</option>
                                  {% endif %}
                                  
                                {% endfor %}
                                </select>
                              </div>
                              <div class="mb-3">
                                <label for="" class="form-label">Imagen</label>
                                <input type="file" class="form-control" id="imagen"  name="imagen" >
                              </div>
                              <div class="mb-3">
                                <label for="id_precio"class="form-label">Precio : </label>
                                <input type="number" id="nuevo_precio" name="nuevo_precio" min="0"placeholder="{{ juego.precio }}">
                                </div>
                              <div class="d-grid">
                                  <button type="submit" class="btn btn-outline-primary">ENVIAR</button>
                              </div>
                            </form>
                        </div>
                      </div>
                    
    
    
                </div>
               
            </div>
        </div>
{% endblock %}


store/templates/juegos/juegos_show.html
{% extends 'base.html' %}

{% block css %}
    
{% endblock %}


{% block contenido %}

<center>
<h1>Juegos {{ juego.nombre }}</h1>
<br>
  <div class="container">
      <div class="col-12 col-sm-6 col-md-6">
        <div class="card-header">

          <img src="{{juego.imagen.url}}" class="card-img-top" alt="" class="...">
        <div class="card-body">
          <br>
          <h2 class="card-title">{{ juego.nombre }}</h2>
          <br>
          <p class="card-text">{{ juego.descripcion }}</p>
          <br>
          {%if juego.id == 62%}
          <a href="{% url 'detalle_juego_api' %}" class="boton2">Personajes</a>
          {% endif %}
          {%if juego.id == 63%}
          <a href="{% url 'personajes_juego_api' %}" class="boton2">Personajes</a>
          {% endif %}
        </div>
      </div>
    <div>
    <h2>Valor del juego $ {{ juego.precio }}</h2>
    <a href="{% url 'agregar_al_carrito' juego.id %}" class="btn btn-primary">Añadir al carrito</a>
    </div>
  </center>
  
<footer>

  <h5> @Copyright Lhia Cadiz /Juan Miranda </h5>
  
</footer>
{% endblock %}


store/templates/juegos/pago.html
{% extends 'base.html' %}
{% load static %}




{% block contenido %}


    <div class="col-12">
        <img src="{% static 'imagenes/graciasCompra.png' %}" alt="Gracias por comprar"></a>
    </div>


    <footer>
        <div class="column4">
            <h5> @Copyright Lhia Cadiz /Juan Miranda </h5>
        </div>

    </footer>
  {% endblock %}

store/templates/juegos/supervivencia.html
{% extends 'base.html' %}



{% block contenido %}
<h1>Juegos SUPERVIVENCIA</h1>
<div class="container">
  <div class="row">
    
      {% for juego in juegos_supervivencia %}
 
    
      <div class="col-12 col-sm-6 col-md-4 mb-4">
        <div class="card">
          <a href= "{% url 'juegos_show' id=juego.id %}">
          <img src="{{ juego.imagen.url }}" class="card-img-top" alt="...">
          <div class="card-body">
            <h2 class="card-title"> {{juego.nombre}} </h2>
            </a>
            <p class="card-text">{{ juego.descripcion }}</p>
            <a href="{% url 'agregar_al_carrito' juego.id %}" class="btn btn-primary">Añadir al carrito</a>
          </div>
        </div>
      </div>
    
  
      {% endfor %}
    
  </div>
</div>
<footer>

  <h5> @Copyright Lhia Cadiz /Juan Miranda </h5>

</footer>
{% endblock %}
